[mainnet]


[all:vars]
ansible_port=22
ssh_file_path=ADD_FILE_PATH
user_home="{{ ansible_env.HOME }}"
path="/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin:/usr/local/go/bin:/{{ user_home }}/go/bin"
digital_ocean_api_token=ADD_HERE
user=root
region=blr1
ssh_key_name=ADD_HERE
