[mainnet]


[all:vars]
ansible_port=22
ssh_file_path=/home/vitwit/.ssh/id_rsa.pub

user_home="{{ ansible_env.HOME }}"
path="/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin:/usr/local/go/bin:/{{ user_home }}/go/bin"

digital_ocean_api_token=REPLACE
user=root
region=blr1
ssh_key_name=Ritvik
