[IP]
server ansible_host=a.b.c.d ansible_user=root


[all:vars]

user_home="{{ ansible_env.HOME }}"
path="/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin:/usr/local/go/bin:{{ user_home }}/go/bin"
network= #github repo name ex: passage
node_home= #the node home for the chain ex:'.passage'
daemon= #the daemon name of the network ex:passage
node_version= #Current node version of the chain ex:v2.4.0
network_upgrade_version=#The version you want to upgrade to ex:v2.5.0
network_upgrade_name=#The upgrade plan name specified ex:v2.5
repo= #The network repo url https://github.com/envadiv/Passage3D       
denom=# The denom of the network ex:upasg
minimum_gas_price=#The minimum gas price ex: 12.5upasg
go_version=#Go version for the project ex:1.21.6
state_export_file_path=#The path to state export file present on the same server where the playbook runs ex:"/root/passage-export-12591387.json"
validator_name=#The name of the validator ex: passage-validator
fullnode_name=#The name of the fullnode ex: passage-fullnode
sdk_version=#The sdk version used in the project. Please specify the full version ex :"v0.45.16"
addr_prefix=#The address prefix o the network ex:"pasg"
ping_repo="https://github.com/ping-pub/explorer.git"
upgrade_height=#The upgrade height where the network upgrade takes place ex:12591507
upgrade_deposit=#The upgrade deposit ex: 1000





top_self_delegation_address=# Self delegation address of the top validator in the network
top_self_delegation_public_key=# Self delegation public key of the top validator in the network
top_operator_address=# The valoperator address of the validator
top_operator_pubkey=# The valoper public key of the validator
top_hexaddr=# The hex address of the validator
top_consensus_address=# The consensus address of the validator