[IP]
server ansible_host=a.b.c.d ansible_user=root


[all:vars]

user_home="{{ ansible_env.HOME }}"

path="/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin:/usr/local/go/bin:{{ user_home }}/go/bin"
#github repo name
network=passage

#the node home for the chain
node_home=.passage

#the daemon name of the network
daemon=passage

#Current node version of the chain
node_version=v2.4.0

#The version you want to upgrade to
network_upgrade_version=v2.5.0

#The upgrade plan name specified
network_upgrade_name=v2.5

#The network repo url
repo=https://github.com/envadiv/Passage3D

#The denom of the network
denom=upasg

#The minimum gas price of the network
minimum_gas_price=12.5upasg

#Go version for the project
go_version=1.21.6

#The path to state export file present on local machine where ansible is running
state_export_file_path=/root/passage-export-12591387.json

#The name of the validator
validator_name=passage-validator

#The name of the fullnode
fullnode_name=passage-fullnode

#The sdk version used in the project. Please specify the full version
sdk_version=v0.45.16

#The address prefix of the network
addr_prefix=pasg

ping_repo="https://github.com/ping-pub/explorer.git"

#The upgrade height where the network upgrade takes place
upgrade_height=12591507

#The upgrade deposit required for the  network upgrade
upgrade_deposit=1000

#Self delegation address of the top validator in the network
top_self_delegation_address=pasg1fcwhweq2qtd5aj702v4pj0apfxt8nrgp68thu3

#Self delegation public key of the top validator in the network
top_self_delegation_public_key=Arrzn+YFjqXhmr8/QtO+uymFwrXIJsmYTZ/Lltwfj4mA

#The valoperator address of the validator
top_operator_address=pasgvaloper1fcwhweq2qtd5aj702v4pj0apfxt8nrgpfmplad

#The valoper public key of the validator
top_operator_pubkey=ZLE8kDUgXL4SpaMa2rKouWNBLjo+lXkSlkb92SsWXxA=

#The hex address of the validator
top_hexaddr=0173FD24D68B059940736F29EEB5083D98F7AA44

# The consensus address of the validator
top_consensus_address=pasgvalcons1q9el6fxk3vzejsrndu57adgg8kv002jy3sanfe