---
- name: Initialize the chain
  command: '{{ daemon }} init {{ node_name }} --chain-id {{ chain_id }}'
  environment:
    PATH: '{{ path }}'


- name: Add Keys
  command: '{{ daemon }} keys add {{ key_name }} --keyring-backend test'
  environment:
    PATH: '{{ path }}'

- name: Add genesis account     
  command: '{{ daemon }} genesis add-genesis-account {{ key_name }} 100000000000stake --keyring-backend=test'
  environment:
    PATH: '{{ path }}'


- name: Gentx Command
  command: '{{ daemon }} genesis  gentx {{ key_name }} 100000000stake --chain-id {{ chain_id }} --keyring-backend test'
  environment:
    PATH: '{{ path }}'

- name: Collect gentxs
  command: '{{ daemon }} genesis  collect-gentxs'
  environment:
    PATH: '{{ path }}'    
   


- name: Update minimum gas price
  lineinfile:
    path: '{{ user_dir }}/{{ folder }}/config/app.toml'
    regexp: '^minimum-gas-prices ='
    line: 'minimum-gas-prices = "{{ minimum_gas_price }}"'
    state: present
  when: minimum_gas_price is defined
