---
- name: Copy the service file
  become: true
  template:
    src: 'service_file.j2'
    dest: '/etc/systemd/system/{{ network }}.service'
    owner: root
    group: root
    mode: '0644'

- name: Start the service file
  systemd:
    name: '{{ network }}'
    state: started
    enabled: yes