# ---

#  - name: Install npm
#    apt:
#      name: npm
#      state: present
 
# - name: Install nvm
#   shell: >
#     curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.4/install.sh | bash &&
#     export NVM_DIR="{{ user_dir }}/.nvm" &&
#     [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" &&
#     [ -s "$NVM_DIR/bash_completion" ] && . "$NVM_DIR/bash_completion"
#   args:
#     executable: /bin/bash

# - name: Install Node.js
#   shell: >
#     . "{{ user_dir }}/.nvm/nvm.sh" &&
#     nvm install v18.19.0
#   environment:
#     NVM_DIR: "{{ user_dir }}/.nvm"
#     PATH: "{{ user_dir }}/.nvm/versions/node/v18.19.0/bin:{{ ansible_env.PATH }}"
#   become: yes

# - name: Update global PATH
#   lineinfile:
#     path: /etc/environment
#     line: 'PATH="{{ user_dir }}/.nvm/versions/node/v18.19.0/bin:{{ ansible_env.PATH }}"'
#   become: yes




#  - name: Install Yarn globally
#    npm:
#      name: yarn
#      global: yes


# ---
# - name: Install npm
#   apt:
#     name: npm
#     state: present
# - name: Install Yarn globally
#   npm:
#     name: yarn
#     global: yes    

# - name: Install nvm
#   shell: >
#     curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.4/install.sh | bash &&
#     export NVM_DIR="{{ user_dir }}/.nvm" &&
#     [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" &&
#     [ -s "$NVM_DIR/bash_completion" ] && . "$NVM_DIR/bash_completion"
#   args:
#     executable: /bin/bash

# - name: Install Node.js
#   shell: >
#     . "{{ user_dir }}/.nvm/nvm.sh" &&
#     nvm install v18.19.0
#   environment:
#     NVM_DIR: "{{ user_dir }}/.nvm"
#     PATH: "{{ user_dir }}/.nvm/versions/node/v18.19.0/bin:{{ ansible_env.PATH }}"
#   become: yes

# - name: Update global PATH
#   lineinfile:
#     path: /etc/environment
#     line: 'PATH="{{ user_dir }}/.nvm/versions/node/v18.19.0/bin:{{ ansible_env.PATH }}"'
#   become: yes
 








---
- name: Install nvm
  shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.4/install.sh | bash &&
    export NVM_DIR="{{ user_dir }}/.nvm" &&
    [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" &&
    [ -s "$NVM_DIR/bash_completion" ] && . "$NVM_DIR/bash_completion"
  args:
    executable: /bin/bash

- name: Install Node.js
  shell: >
    . "{{ user_dir }}/.nvm/nvm.sh" &&
    nvm install v18.19.0
  environment:
    NVM_DIR: "{{ user_dir }}/.nvm"
    PATH: "{{ user_dir }}/.nvm/versions/node/v18.19.0/bin:{{ ansible_env.PATH }}"
  become: yes

- name: Update global PATH
  lineinfile:
    path: /etc/environment
    line: 'PATH="{{ user_dir }}/.nvm/versions/node/v18.19.0/bin:{{ ansible_env.PATH }}"'
  become: yes

- name: Install npm
  shell: >
    . "{{ user_dir }}/.nvm/nvm.sh" &&
    nvm install-latest-npm
  environment:
    NVM_DIR: "{{ user_dir }}/.nvm"
    PATH: "{{ user_dir }}/.nvm/versions/node/v18.19.0/bin:{{ ansible_env.PATH }}"

- name: Install yarn
  shell: >
    . "{{ user_dir }}/.nvm/nvm.sh" &&
    npm install --global yarn
  environment:
    NVM_DIR: "{{ user_dir }}/.nvm"
    PATH: "{{ user_dir }}/.nvm/versions/node/v18.19.0/bin:{{ ansible_env.PATH }}"




