---
- name: Create NVM directory
  file:
    path: "{{ user_home }}/.nvm"
    state: directory
    mode: "0755"

- name: Download nvm installer with curl
  command: curl -fsSL https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.4/install.sh -o {{ user_home }}/install_nvm.sh
  args:
    creates: "{{ user_home }}/install_nvm.sh"
  environment:
    HOME: "{{ user_home }}"

- name: Run nvm install script
  shell: bash "{{ user_home }}/install_nvm.sh"
  args:
    executable: /bin/bash
  environment:
    NVM_DIR: "{{ user_home }}/.nvm"

- name: Install Node.js
  shell: >
    . "{{ user_home }}/.nvm/nvm.sh" &&
    nvm install v18.19.0
  environment:
    NVM_DIR: "{{ user_home }}/.nvm"
    PATH: "{{ user_home }}/.nvm/versions/node/v18.19.0/bin:{{ ansible_env.PATH }}"

- name: Update user's PATH in .bashrc
  lineinfile:
    path: "{{ user_home }}/.bashrc"
    line: 'export PATH="{{ user_home }}/.nvm/versions/node/v18.19.0/bin:$PATH"'
  become_user: "{{ ansible_user }}"

- name: Install npm
  shell: >
    . "{{ user_home }}/.nvm/nvm.sh" &&
    nvm install-latest-npm
  environment:
    NVM_DIR: "{{ user_home }}/.nvm"
    PATH: "{{ user_home }}/.nvm/versions/node/v18.19.0/bin:{{ ansible_env.PATH }}"

- name: Install yarn
  become: true
  shell: >
    . "{{ user_home }}/.nvm/nvm.sh" &&
    npm install --global --unsafe-perm=true yarn
  environment:
    NVM_DIR: "{{ user_home }}/.nvm"
    PATH: "{{ user_home }}/.nvm/versions/node/v18.19.0/bin:{{ ansible_env.PATH }}"

- name: Install ping_explorer
  git:
    repo: "{{ ping_repo }}"
    dest: "{{ user_home }}/explorer"
    version: "f0120a4a9f1a96f596139f36a9030fd05f227d8b"

- name: Install nginx
  become: true
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Remove contents of mainnet directory
  file:
    path: "{{ user_home }}/explorer/chains/mainnet"
    state: absent
  become: true

- name: Recreate mainnet directory
  file:
    path: "{{ user_home }}/explorer/chains/mainnet"
    state: directory
  become: true

- name: Copy the sample json file
  become: true
  template:
    src: "{{ playbook_dir }}/templates/explorer-config.j2"
    dest: "{{ user_home }}/explorer/chains/mainnet/local-testnet.json"

- name: Remove contents of /var/www/html
  become: true
  file:
    path: "/var/www/html/"
    state: absent

- name: Recreate /var/www/html directory
  become: true
  file:
    path: "/var/www/html/"
    state: directory

- name: Build the explorer
  become: true
  shell: >
    . "{{ user_home }}/.nvm/nvm.sh" && export PATH="{{ ansible_env.PATH }}:{{ user_home }}/.nvm/versions/node/v18.19.0/bin" && cd '{{ user_home }}/explorer' && yarn install --ignore-engines && yarn build
  args:
    chdir: "{{ user_home }}/explorer"

- name: Move the data inside dist folder to /var/www/html
  become: true
  shell: cp -r dist/* /var/www/html/
  args:
    chdir: "{{ user_home }}/explorer"
